version: "2"

submodules:
  include: all

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.10"

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
